name: BasicAnnouncer
main: UnknownBallin\BasicAnnouncer\Announce
author: UnknownBallin
version: 1.0.0
api: 3.0.0

commands:
  announce:
    description: "Broadcast your message"
    aliases:
    - announcement
    - broadcast
    - bcast
    - cast

permissions:
  ba.cmd.announce:
    default: op